number=input()
while(number!="Quit"):
    number=int(number)
    if(number==0):
        print("ZERO")
    elif(number>0):
        print("POSITIVE")
    else:
        print("NEGETIVE")
    number=input()
