numbers = [12, 45, 65, 23, 89, 78, 11]

# print(numbers[3 : -5])
# print(numbers[2 : 7: 1])
# print(numbers[:])
# print(numbers[: : -1])
numbers[len(numbers):]=[50]
# print(numbers[:])
numbers.insert(2, 76)
# print(numbers[:])
numbers.insert(len(numbers), 863)
# print(numbers[:])
numbers.remove(23)
# print(numbers[:])
# numbers.clear()
# print(numbers[:])
numbers.pop()
# print(numbers[:])
numbers.insert(0, 78)
# print(numbers[:])
# print(numbers.count(78))
numbers.sort()
# print(numbers[:])
numbers.reverse()
# print(numbers[:])
numbers.copy()
# print(numbers[:])
print(numbers.index(50))
print(numbers)
